### ISSUE TITLE
Citation? (bibtex)

### ISSUE THREAD

**Issue by aluo-x** [tatsy/mcubes_pytorch#3]
A recent project of mine has used this library pretty extensively, I would like to cite this tool.

Is there a citation and/or a paper where you use this tool?

For example: Trimesh has this citation in their [github](https://github.com/mikedh/trimesh) (see bottom of page)

```
@software{trimesh,
	author = {{Dawson-Haggerty et al.}},
	title = {trimesh},
	url = {https://trimsh.org/},
	version = {3.2.0},
	date = {2019-12-8},
}
```

**Comment by tatsy** [comment]
Hi @aluo-x,

Thank you very much for your suggestion. Honestly speaking, I am not really sure that this repo deserves to be cited because this software is rather straightforward implementation of Marching Cubes using GPU, and wrapped by PyTorch CUDA/C interop.

By the way, if you will kindly cite this repo, please use the following as a BibTeX entry.

```bibtex
@software{mcubes_pytorch,
  author={Tatsuya Yatagawa},
  title={mcubes_pytorch: PyTorch Implementation for Marching Cubes},
  url={https://github.com/tatsy/mcubes_pytorch/},
  date={2020-06-20}
}
``` 

Thank you.

**Comment by aluo-x** [comment]
Great! Much appreciated.
