### ISSUE TITLE
Would it run faster than scipy implementation?

### ISSUE THREAD

**Issue by MingwuZheng** [tatsy/mcubes_pytorch#7]

**Comment by tatsy** [comment]
I think so because `torchmcubes` uses GPU. Why not compare it first?

**Comment by aluo-x** [comment]
It is significantly faster. But the meshes generated by this package is lower quality than scikit-image, since scikit-image uses the lewiner variant which resolves ambiguities. 

Generally the meshes generated by this package has many small holes.

**Comment by wangxihao** [comment]
Great work !But generally the meshes generated by this package has indeed many small holes, don't know how to fix it?

**Comment by tatsy** [comment]
Hi @wangxihao,

As @aluo-x explained kindly, the small holes you found are because this package implements the simplest marching cubes method proposed by Lorensen et al. in 1987, which generates a set of triangles for each cell independently and does not account for their coherence over adjacent cells, though the coherency was later accounted for by Lewiner's variant.

You can find the article on Lewiner's variant in:
https://www.tandfonline.com/doi/abs/10.1080/10867651.2003.10487582

In addition, you can sidestep the problem of small holes by implementing other variants, such as marching tetrahedra and dual contouring, though I do not plan to do so.

Hope it helps.

**Comment by wangxihao** [comment]
Thanks for your reply(answer) kindly!

Tatsuya Yatagawa ***@***.***> 于2022年7月11日周一 16:28写道：
